AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: HW3 Photo Album
Resources:
  HW3LF1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw3lf1
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lf1/lambda_function.py
      Description: 'Generates labels for images'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::157934964394:role/service-role/lf1-custom-role'
      # Events:
      #   ajy6zr9ep2:
      #     Type: Api
      #     Properties:
      #       Path: /photos/{folder}/{item}
      #       Method: put
      Environment:
        Variables:
          REGION: us-east-1


  HW3LF2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw3lf2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lf2/lambda_function.py
      Description: 'Returns Image URLs'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::157934964394:role/lambda_vpc_basic_execution'
      Events:
        ajy6zr9ep2:
          Type: Api
          Properties:
            Path: /search
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
          
          
  HW3LF3:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw3lf3
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lf3/lambda_function.py
      Description: 'For Transcribe'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::157934964394:role/service-role/lf3-role-chulr1hi'
      Events:
        ajy6zr9ep2:
          Type: Api
          Properties:
            Path: /transcriber
            Method: post
      Environment:
        Variables:
          REGION: us-east-1


  HW3LF4:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw3lf4
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lf4/lambda_function.py
      Description: 'For uploading images'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::157934964394:role/service-role/lf4-role-z7935dai'
      Events:
        ajy6zr9ep2:
          Type: Api
          Properties:
            Path: /photos/{folder}/{item}
            Method: put
      Environment:
        Variables:
          REGION: us-east-1


  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: "phot-album-cf"
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: "False"
        InstanceCount: "2"
        ZoneAwarenessEnabled: "true"
        InstanceType: "t2.small.elasticsearch"
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: "gp2"
      SnapshotOptions:
        AutomatedSnapshotStartHour: "0"
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: "true"
